### ISSUE TITLE
Incorrectly sorting CSS variables

### ISSUE THREAD

**Issue by alejandroiglesias** [whiteand/sort-css-rules-extension#1]
Hi! In my SCSS file, I use CSS variables and those get sorted incorrectly. Here is an example source before sorting:

```scss
header#main-header {
	--active-border-color: #{theme.color("gray600")};
	--button-bg-color: #{theme.color("primary")};
	--button-color: #{theme.color("white")};
	--header-border-color: #{theme.color("borders")};
	--lettermark-opacity: 1;
	--lettermark-position: 0;
	--logo-color: #{theme.color("primary")};
	--main-nav-bg-color: #{theme.color("white")};
	--main-nav-color: #{theme.color("gray600")};
	--transition-duration: 500ms;
	--transition-easing: cubic-bezier(0.2, 0.0, 0, 1.0);

	// rest of the properties
}
```

After running the command:

```scss
header#main-header {
	z-index: 10;
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	border-bottom: 1px solid var(--header-border-color);
	transition-property: border-color;
	--transition-duration: 500ms;
	transition-duration: var(--transition-duration);
	transition-timing-function: var(--transition-easing);
	--active-border-color: #{theme.color("gray600")};

	--button-bg-color: #{theme.color("primary")};
	--button-color: #{theme.color("white")};
	--header-border-color: #{theme.color("borders")};
	--lettermark-opacity: 1;
	--lettermark-position: 0;
	--logo-color: #{theme.color("primary")};
	--main-nav-bg-color: #{theme.color("white")};
	--main-nav-color: #{theme.color("gray600")};
	--transition-easing: cubic-bezier(0.2, 0.0, 0, 1.0);
}
```
Notice vars are non-sorted but also intermixed with the properties.
